"""add is_recommendation flag to recipes

Revision ID: 6b43d1e54fe0
Revises: f53637646efe
Create Date: 2026-07-31 01:32:23.382026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b43d1e54fe0'
down_revision: Union[str, Sequence[str], None] = 'f53637646efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('is_recommendation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'is_recommendation')
    # ### end Alembic commands ###
