"""add ingredient colloquial_quantity field

Revision ID: 7636834d477b
Revises: 79eb8cc5df8d
Create Date: 2026-07-28 20:16:19.821343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7636834d477b'
down_revision: Union[str, Sequence[str], None] = '79eb8cc5df8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('colloquial_quantity', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'colloquial_quantity')
    # ### end Alembic commands ###
