"""add ingredient component field

Revision ID: 79eb8cc5df8d
Revises: 7368267b0322
Create Date: 2026-07-28 19:49:24.439608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79eb8cc5df8d'
down_revision: Union[str, Sequence[str], None] = '7368267b0322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('component', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'component')
    # ### end Alembic commands ###
